apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: webapps
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGd1bmRnbXpy
  CLOUDINARY_KEY: NjYyODc1MzI0MzQyMTc1
  CLOUDINARY_SECRET: WVhHNmpUVlZZTE8wTE9nRVhIZThYZEZtS1Zn
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lkbUZ0YzJrMU1UY3dJaXdpWVNJNkltTnRiM1JzY0RjNFpUQTJNV0l5Y1hGM2FIWTBkRzk0TjNVaWZRLkpJb1VDS3k4YllMZlRmWllHS0ZOYXc=
  DB_URL: bW9uZ29kYitzcnY6Ly92YW1zaTUxNzA6VmFtc2k1MTcwJTQwQGNsdXN0ZXIwLnZlOTVsNWgubW9uZ29kYi5uZXQveWVscGNhbXA/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
